### PR TITLE
textmate no longer uses the Avian folder

### PR DESCRIPTION
**Pull request by perzeababa**

### CODE REVIEW

**Comment by jjeising** [comment]
Thanks! I would like to merge this, but I think we need `Textmate` in the path, instead of removing it completely.

**Comment by perzeababa** [comment]
"Textmate" was never removed since this reference exists in the  Application support Library folder

**Comment by jjeising** [comment]
Sorry, that was a bit unclear on my part. Your new suggested path is

```
Library/Application Support/Pristine Copy/Bundles/
```
while it probably should be
```
Library/Application Support/TextMate/Pristine Copy/Bundles/
```
Can you change that?

**Comment by perzeababa** [comment]
done!

**Comment by jjeising** [comment]
Thanks, merged.

**Pull request merged**
